[versions]
agp = "8.13.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
retrofitVersion = "3.0.0"
retrofitOkhttp3 = "5.2.1"
retrofitOkhttp = "4.12.0"
coroutines = "1.10.2"
lifecycle = "2.9.4"
glidev = "5.0.5"
youtube = "13.0.0"
chromecast = "21.4.0"
pipe = "v0.24.8"
exoplayer = "1.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitVersion" }
retrofit-okhttp3 = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "retrofitOkhttp3" }
retrofit-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "retrofitOkhttp" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glidev" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glidev" }
android-youtube = { group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "core", version.ref = "youtube" }
chromecast = { group = "com.google.android.gms", name = "play-services-cast-framework", version.ref = "chromecast" }
newpipe = { group = "com.github.TeamNewPipe", name = "NewPipeExtractor", version.ref = "pipe" }
exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "exoplayer" }
exoplayer-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "exoplayer" }
exoplayer-common = { group = "androidx.media3", name = "media3-common", version.ref = "exoplayer" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

